### ISSUE TITLE
A few notes

### ISSUE THREAD

**Issue by NateChoe1** [hanilr/parser-acc#1]
I saw your post on r/c_programming and I thought I'd leave a few notes here.

Your main function doesn't check if there's actually an argument supplied, and just immediately sets `file_content` based on `argv[1]`. `argc` contains the amount of arguments supplied to the program, so you can fix this by just checking the value of `argc`:
```
if (argc < 2) {
    fprintf(stderr, "Usage: %s [file to parse]\n", argv[0]);
    return 1
}
```
The pointer returned by malloc() isn't necessary cleared, which means that the string returned by read_file isn't necessarily null terminated, Because of the way the C standard library is implemented and the fact that this specific malloc() is called so early, the string will actually be null terminated, which is why you haven't been getting any errors, so you may not have noticed.

You're using the magic number 10 a lot in your code (parser.c:5, util.c:64, util.c:71) to represent the newline. You should instead use `'\n'` to represent newlines for a couple of reasons, the first being that "magic numbers" like this in code makes the code harder to understand, but also C is such an old language that there isn't an official C character set, so 10 isn't always a newline. I doubt your code will ever run on a computer from the 60s using EBCDIC, but ANSI C intentionally doesn't specify a character set. You use another similar "magic number" in parser.c:41.

You have a memory leak in parser.c:19, you're allocating memory but never freeing it. C is such an old language that it has no automatic garbage collection, which basically means that once you ask for memory, you have to give it back. Once you're done using a pointer obtained from `malloc()`, call `free()` to give that memory back to the C standard library so that it doesn't just sit there unused. A second call to `malloc()` may use this newly available memory, which already has the data you put in there before, which is why memory obtained from `malloc()` is "uninitialized"

get_line is quite inefficient. You can imagine getting the last line from a file would require you to go through the entire file, while copying each line only to erase it immediately afterwards until the last line. Going through every line of the file has O(n^2) efficiency, which basically means that if you have n times more lines, the program runs n^2 times slower. For example, if you triple the lines, the program runs 9 times slower because the file is larger and you have to go through the file over and over again more times. There are a coupe methods I can think of you can use to make this better:

1. Go through the entire file once, finding the positions of each line and storing them so that they can be referenced later
2. Don't read the entire file into memory, just keep the `FILE *` pointer and create a `get_next_line` function which gets the next line from a file

`subinstr` seems pretty similar to the standard library function `strstr`, which returns a pointer to the location a string can be found within another string, or `NULL` if the string doesn't appear in the other. `subinstr(char *str, char *chr)` can be replaced with `strstr(char *str, char *chr) == NULL`, The standard library function `strchr` works in a similar way to `strstr` but on single characters and is faster, so you can replace all the single character `subinstr` calls. `dislen` can similarly be replaced with strstr.

parser.c:48 is unnecessary (I think)

`strlen(str) > word_pos` can be replaced with `str[word_pos] != '\0'` or even just `str[word_pos]` because the last character of a string is always going to be '\0'. strlen has to go through the entire string to find the length, so repeated calls to strlen is inneficient. A similar thing happens in util.c:24. 

Overall this code is pretty solid, you've got a few issues with memory management, and you could make better use of the C standard library, but there's a decent foundation to build something pretty good.

**Comment by hanilr** [comment]
Thank you for your thorough review of my project and your feedback :)

My purpose in doing this project was to learn more about memory management and how a compiler works. For this reason, I decided to do such a project because I thought that making a parser would improve me enough. 

The points you mentioned are overlooked and I don't know enough about standard libraries.  Thanks to you, I will be able to improve myself more easily.  You can be sure that I will fix the issues you mentioned in the next update.

Also, thank you for thinking that the code I wrote is a solid foundation for doing things.
